Algoritmo "area_do_retângulo"
// Descrição   : Calculo da area do retangulo
// Autor(a)    : Rúben Filipe
// Data atual  : 14/09/2017
Var comprimento, largura, area: real
// Seção de Declarações das variáveis 
Inicio
 escreva("Qual é o comprimento do retangulo?")
 leia (comprimento)
 escreva ( "Qual a largura do retangulo?")
 leia (largura)
 
 area <- comprimento * largura
 escreva ("A area é", area)
Fimalgoritmo