Algoritmo "Volume_do_Paralelopipedo"
// Descrição   : Calcular Volume do Paralelopipedo
// Autor(a)    : Ruben Filipe
// Data atual  : 20/09/2017
Var comprimento, altura, largura, volume: real
Inicio
Escreva ("Qual o comprimento?")
Leia (comprimento)
Escreva ("Qual a altura?")
Leia (altura)
Escreva ("Qual a largura?")
Leia (largura)
Volume <- comprimento * altura * largura
Escreva ("O volume é",volume)
Fimalgoritmo